config/routes.rb
RedditClone::Application.routes.draw do
  resources :comments

  resources :links

  resources :subs

  resources :users
  resource :session, only: [:create, :new, :destroy]
  root to: "sessions#new"

end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Sub < ActiveRecord::Base
  MIN_TITLE_LEN = 3
  validates :title, :length => { :minimum => MIN_TITLE_LEN }
  validates_presence_of :user

  belongs_to :user

  has_many :link_subs, inverse_of: :sub
  has_many :links, through: :link_subs, inverse_of: :subs


  # def to_s
  #   'test'
  # end
  #
  # def inspect
  #   'this is a sub'
  # end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_sub, only: [:show, :edit, :update, :destroy]

  # GET /subs
  # GET /subs.json
  def index
    @subs = Sub.all
  end

  # GET /subs/1
  # GET /subs/1.json
  def show
  end

  # GET /subs/new
  def new
    @sub = Sub.new
  end

  # GET /subs/1/edit
  def edit
  end

  # POST /subs
  # POST /subs.json
  def create
    @sub = Sub.new(sub_params)

    respond_to do |format|
      if @sub.save
        format.html { redirect_to @sub, notice: 'Sub was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sub }
      else
        format.html { render action: 'new' }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subs/1
  # PATCH/PUT /subs/1.json
  def update
    respond_to do |format|
      if @sub.update(sub_params)
        format.html { redirect_to @sub, notice: 'Sub was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subs/1
  # DELETE /subs/1.json
  def destroy
    @sub.destroy
    respond_to do |format|
      format.html { redirect_to subs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub
      @sub = Sub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_params
      params.require(:sub).permit(:user_id, :title)
    end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<%= form_for(@sub) do |f| %>
  <% if @sub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub.errors.count, "error") %> prohibited this sub from being saved:</h2>

      <ul>
      <% @sub.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subs/edit.html.erb
<h1>Editing sub</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub %> |
<%= link_to 'Back', subs_path %>

app/views/subs/index.html.erb
<h1>Listing subs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |sub| %>
      <tr>
        <td><%= sub.user %></td>
        <td><%= sub.title %></td>
        <td><%= link_to 'Show', sub %></td>
        <td><%= link_to 'Edit', edit_sub_path(sub) %></td>
        <td><%= link_to 'Destroy', sub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub', new_sub_path %>

app/views/subs/new.html.erb
<h1>New sub</h1>

<%= render 'form' %>

<%= link_to 'Back', subs_path %>

app/views/subs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @sub.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @sub.title %>
</p>

<%= link_to 'Edit', edit_sub_path(@sub) %> |
<%= link_to 'Back', subs_path %>